/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BLL.EmployeeTrainings;
import DAL.CertifiableInterface;
import DAL.CertifiableRepository;
import DAL.EmployeeInterface;
import DAL.EmployeeRepository;
import DAL.EmployeeTrainingsException;
import DAL.EmployeeTrainingsInterface;
import DAL.EmployeeTrainingsRepository;
import DAL.TrainingStatusInterface;
import DAL.TrainingStatusRepository;
import DAL.TrainingTypesInterface;
import DAL.TrainingTypesRepository;
import MODEL.CertifiableComboBoxModel;
import MODEL.EmployeeComboBoxModel;
import MODEL.EmployeeTrainingsTableModel;
import MODEL.TrainingStatusComboBoxModel;
import MODEL.TrainingStatusTableModel;
import MODEL.TrainingTypesComboBoxModel;
import MODEL.TrainingTypesTableModel;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author BesaC
 */
public class EmployeeTrainingsForm extends javax.swing.JInternalFrame {

     
    EmployeeTrainingsInterface etr = new EmployeeTrainingsRepository();
    EmployeeTrainingsTableModel ettm = new EmployeeTrainingsTableModel();

    TrainingStatusInterface tsr = new TrainingStatusRepository();
    TrainingStatusComboBoxModel tscbm = new TrainingStatusComboBoxModel();

    CertifiableInterface cr = new CertifiableRepository();
    CertifiableComboBoxModel ccbm = new CertifiableComboBoxModel();

    EmployeeInterface er = new EmployeeRepository();
    EmployeeComboBoxModel ecbm = new EmployeeComboBoxModel();

    TrainingTypesInterface ttr = new TrainingTypesRepository();
    TrainingTypesTableModel tttm = new TrainingTypesTableModel();
    TrainingTypesComboBoxModel ttcbm = new TrainingTypesComboBoxModel();
    TrainingStatusTableModel tstm = new TrainingStatusTableModel();


    EmployeeTrainingsSearchJFRAME sjf ;
    EmployeeTrainingCertificationJFRAME ejf;
    
    public EmployeeTrainingsForm() {
        initComponents();
        tableLoad();
    }
    public  void reLoad(){
        Date date = new Date();
        List<EmployeeTrainings> list = null;

        try {
            list = etr.findAll();
            
            for (EmployeeTrainings list1 : list) {
                if(list1.getTrainingStatus().equals(tstm.getTrainingStatus(2))){
                    continue;
                    
                }else if(list1.getTrainingStatus().equals(tstm.getTrainingStatus(3))){ // tStatus ----> "PLANNED"

                        if(date.compareTo(list1.getStartDate()) < 0  ){
                            list1.setTrainingStatus(tstm.getTrainingStatus(1)); // tStatus ---> "ONGOING"
                        }else{
                            continue;
                        }                    
                }else{
                        if(date.compareTo(list1.getEndDate()) > 0){
                            list1.setTrainingStatus(tstm.getTrainingStatus(2));
                        }else {
                            continue;
                        }
                }
            }
        } catch (EmployeeTrainingsException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
        ettm = new EmployeeTrainingsTableModel(list);
        table.setModel(ettm);
    }
    public void tableLoad() {
        try {
            List<EmployeeTrainings> list = etr.findAll();
            ettm = new EmployeeTrainingsTableModel(list);
            table.setModel(ettm);
            ettm.fireTableDataChanged();
            tabelaSelectedIndexChange();
            reLoad();
        } catch (EmployeeTrainingsException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }





    public void tabelaSelectedIndexChange() {
        final ListSelectionModel rowSM = table.getSelectionModel();

        rowSM.addListSelectionListener(new ListSelectionListener() {

            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (e.getValueIsAdjusting()) {
                    return;
                }

                ListSelectionModel rowSM = (ListSelectionModel) e.getSource();
                int selectedIndex = rowSM.getAnchorSelectionIndex();
                if (selectedIndex > -1) {
                    
                    EmployeeTrainings et = ettm.getEmployeeTrainings(selectedIndex);
                    
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        searchBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(table);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("Search  Employee Trainings ");

        jButton1.setText("To Certify : ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 738, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchBtn)
                    .addComponent(jButton1))
                .addGap(68, 68, 68)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ejf = new EmployeeTrainingCertificationJFRAME();
        ejf.setVisible(true);
        if(sjf != null){
            sjf.setVisible(false);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed

        sjf = new EmployeeTrainingsSearchJFRAME();
        sjf.setVisible(true);
        if(ejf != null){
        
            ejf.setVisible(false);
        }
    }//GEN-LAST:event_searchBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
